### PR TITLE
Google Login: Migrate to OAuth

### LINKED ISSUE #249: Google Login: Migrate to OAuth
OpenID is no longer supported so we must transition to using OAuth natively on the device.

### PR DESCRIPTION
**Pull request by marczych**
Google login through OpenID has been deprecated for a little while now so
we have to migrate to Google OAuth. This results in a much better user
experience because it goes through the native interface and doesn't require
the user to enter their credentials.

This also increases the `minSdkVersion` to `9` which is android 2.3. This is
required for Google Play Services which provides the Google Login
functionality. Android 2.2 only makes up 0.65% of installs currently. It's
unfortunate to lose them but the old app will still work for them.

QA
==

 - Check Google login on a few places that require it:
   - Media manager
   - Favorite guides
   - Favoriting a guide
   - etc.
 - Test on various devices:
   - Android 2.3
   - Android 5+
   - Tablet
   - Phone
 - Test in both orientations:
   - Portrait
   - Landscape
 - Unexpected actions:
   - Decline permissions
   - Cancel dialogs
   - Change orientations
 - Test on various accounts:
   - No associated iFixit account
   - iFixit account with permissions accepted through the web signin
   - iFixit account after prior sign in on Android

Closes #249

### CODE REVIEW

**Comment by grantwhiting** [comment]
Tested on
* HTC Nexus 9 with Android 5
* Asus Nexus 7 with Android 4.4.2
* HTC Evo running Android 2.3.5

The Nexus 9 and 7 worked fine with logging in through Google+ at first under the ifixitdev@gmail.com but when I tried to add my personal Google+ account the app would no longer allow me to log in through Google. Even after I removed my personal account.

The HTC Evo never actually successfully logged in through Google. I kept getting an error message stating that an error occurred while trying to load content from our servers.

**Comment by marczych** [comment]
> The Nexus 9 and 7 worked fine with logging in through Google+ at first under the ifixitdev@gmail.com but when I tried to add my personal Google+ account the app would no longer allow me to log in through Google. Even after I removed my personal account. I would get an Invalid Login error.

That is weird. I added and removed Google accounts on my device without any problems. If you can reproduce it and show me that would be great.

> The HTC Evo never actually successfully logged in through Google. I kept getting an error message stating that an error occurred while trying to load content from our servers.

I've been struggling with the same problems on the Evo. I'm pretty sure it's caused by the WiFi going in and out.

Also, I couldn't get the app to run at all on the Evo until cba3f3dc4a2b71fc74d07c3193d4018a4d84a1d9 so it'd be nice to double check that you're on the latest version.

**Comment by timothyasp** [comment]
Looks good! Nice work.  CR :+1:

**Comment by marczych** [comment]
I did some quick testing on various devices with my last commit and everything looked good. @grantwhiting, are you happy with the app the last time you tested it?

**Comment by timothyasp** [comment]
CR :+1:

**Comment by grantwhiting** [comment]
@marczych I tested it again on a few devices and it looks like it's working fine. I'm not running into any login limits.

QA :100:

**Pull request merged**
