### PR TITLE
Translation updates

### PR DESCRIPTION
**Pull request by timothyasp**
Went through and updated all of our translations with the current translations on crowdin.   Also fixed a number of translation LINT problems.

### CODE REVIEW

**Comment by marczych** [comment]
`image_sizes.xml` to `donottranslate.xml` is a bit disappointing because it's always going to take me a bit longer to find that file if I want to see what size images are used where. What does renaming it actually accomplish?

**Comment by timothyasp** [comment]
They won't be submitted to translators and we don't get lint errors.  The alternative is to add `translatable="false"` to all those strings, which isn't the worst thing.

**Comment by marczych** [comment]
> They won't be submitted to translators and we don't get lint errors. The alternative is to add translatable="false" to all those strings, which isn't the worst thing.

Okay, that's fine with me.

CR :tractor:

**Comment by timothyasp** [comment]
Fixes #248

**Pull request merged**
